In [3]:
import pandas as pd

In [4]:
df = pd.read_csv(r'C:\Users\vedant\Downloads\customer_shopping_behavior.csv', encoding = 'unicode_escape')

In [5]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [7]:
df.describe( include = 'all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [28]:
df.isnull().sum()

customer_id                   0
age                           0
gender                        0
item_purchased                0
category                      0
purchase_amount               0
location                      0
size                          0
color                         0
season                        0
review_rating                 0
subscription_status           0
shipping_type                 0
discount_applied              0
previous_purchases            0
payment_method                0
frequency_of_purchases        0
agegroup                      0
purchase_frequancy_days    1147
dtype: int64

In [9]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x : x.fillna(x.median()))

In [10]:
df.columns = df.columns.str.lower()

In [11]:
df.columns = df.columns.str.replace(' ',"_")

In [12]:
 df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [13]:
#label for age group column
labels = ['young_adult','adult','middle_age','sinor']
df['agegroup'] = pd.qcut(df['age'], q = 4 , labels = labels)

In [14]:
df['frequency_of_purchases'].head(10)

0    Fortnightly
1    Fortnightly
2         Weekly
3         Weekly
4       Annually
5         Weekly
6      Quarterly
7         Weekly
8       Annually
9      Quarterly
Name: frequency_of_purchases, dtype: object

In [15]:
# CREATE COLUMN purchase frequancy dATE
frequency_mapping ={
    'Annually' : 365,
    'Quaterly' : 90 ,
    'Weekly' : 7,
    'Fortnightly' : 14,
    'Every 3 month' : 90,
    'Monthly' : 30,
    'Bi-Weekly' : 14 
}

df['purchase_frequancy_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [16]:
df[['purchase_frequancy_days','frequency_of_purchases']].head(10)

   purchase_frequancy_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                      NaN              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                      NaN              Quarterly

In [22]:
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [24]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [27]:
df = df.drop('promo_code_used',axis= 1)

In [29]:
pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl (17.7 MB)
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
    --------------------------------------- 0.3/17.7 MB ? eta -:--:--
   --- ------------------------------------ 1.6/17.7 MB 6.0 MB/s eta 0:00:03
   ----- ---------------------------------- 2.4/17.7 MB 6.3 MB/s eta 0:00:03
   ----- ---------------------------------- 2.6/17.7 MB 4.6 MB/s eta 0:00:04
   ------ --------------------------------- 2.9/17.7 MB 3.6 MB/s eta 0:00:05
   ------- -------------------------------- 3.1/17.7 MB 3.1 MB/s eta 0:00:05
   ------- -------------------------------- 3.4/17.7 MB 2.7 MB/s eta 0:00:06
   -------- ------------------------------- 3.7/17.7 MB 2.5 MB/s eta 0:00:06
   -------- ------------------------------- 3.9/17.7 MB 2.3 MB/s eta 0:00:06
   --------- ------------------------------ 4.2/17.7 MB 2.2 MB/s eta 0:00:07
   ---------- ----------------------------- 4.5/17.7 MB 2.1 MB/s eta 0:00:07
   ---------- ----------------------------- 4.7/17.7 MB 2.0 MB/s eta 0:00:07
   ----------- ---------------------------- 5.0/17.7 MB 2.0 MB/s eta 0:00:07
   ----------- ---------------------------- 5.2/17.7 MB 1.9 MB/s eta 0:00:07
   ------------ --------------------------- 5.5/17.7 MB 1.9 MB/s eta 0:00:07
   ------------- -------------------------- 5.8/17.7 MB 1.8 MB/s eta 0:00:07
   ------------- -------------------------- 6.0/17.7 MB 1.8 MB/s eta 0:00:07
   -------------- ------------------------- 6.3/17.7 MB 1.7 MB/s eta 0:00:07
   -------------- ------------------------- 6.6/17.7 MB 1.7 MB/s eta 0:00:07
   --------------- ------------------------ 6.8/17.7 MB 1.7 MB/s eta 0:00:07
   ---------------- ----------------------- 7.1/17.7 MB 1.6 MB/s eta 0:00:07
   ---------------- ----------------------- 7.3/17.7 MB 1.6 MB/s eta 0:00:07
   ----------------- ---------------------- 7.6/17.7 MB 1.6 MB/s eta 0:00:07
   ----------------- ---------------------- 7.9/17.7 MB 1.6 MB/s eta 0:00:07
   ------------------ --------------------- 8.1/17.7 MB 1.6 MB/s eta 0:00:06
   ------------------- -------------------- 8.7/17.7 MB 1.6 MB/s eta 0:00:06
   -------------------- ------------------- 8.9/17.7 MB 1.6 MB/s eta 0:00:06
   -------------------- ------------------- 9.2/17.7 MB 1.5 MB/s eta 0:00:06
   --------------------- ------------------ 9.4/17.7 MB 1.5 MB/s eta 0:00:06
   --------------------- ------------------ 9.7/17.7 MB 1.5 MB/s eta 0:00:06
   ---------------------- ----------------- 10.0/17.7 MB 1.5 MB/s eta 0:00:06
   ----------------------- ---------------- 10.2/17.7 MB 1.5 MB/s eta 0:00:05
   ----------------------- ---------------- 10.5/17.7 MB 1.5 MB/s eta 0:00:05
   ------------------------ --------------- 10.7/17.7 MB 1.5 MB/s eta 0:00:05
   ------------------------ --------------- 11.0/17.7 MB 1.5 MB/s eta 0:00:05
   ------------------------- -------------- 11.3/17.7 MB 1.5 MB/s eta 0:00:05
   -------------------------- ------------- 11.5/17.7 MB 1.5 MB/s eta 0:00:05
   -------------------------- ------------- 11.8/17.7 MB 1.5 MB/s eta 0:00:05
   --------------------------- ------------ 12.3/17.7 MB 1.5 MB/s eta 0:00:04
   ---------------------------- ----------- 12.6/17.7 MB 1.4 MB/s eta 0:00:04
   ---------------------------- ----------- 12.6/17.7 MB 1.4 MB/s eta 0:00:04
   ----------------------------- ---------- 12.8/17.7 MB 1.4 MB/s eta 0:00:04
   ----------------------------- ---------- 12.8/17.7 MB 1.4 MB/s eta 0:00:04
   ----------------------------- ---------- 13.1/17.7 MB 1.4 MB/s eta 0:00:04
   ------------------------------ --------- 13.6/17.7 MB 1.4 MB/s eta 0:00:03
   ------------------------------ --------- 13.6/17.7 MB 1.4 MB/s eta 0:00:03
   ------------------------------- -------- 13.9/17.7 MB 1.4 MB/s eta 0:00:03
   -------------------------------- ------- 14.4/17.7 MB 1.4 MB/s eta 0:00:03
   --------------------------------- ------ 14.7/17.7 MB 1.4 MB/s eta 0:00:03
   --------------------------------- ------ 14.9/17.7 MB 1.4 MB/s eta 0:00:02
   ---------------------------------- ----- 15.2/17.7 MB 1.4 MB/s eta 0:00:02
   ---------------------------------- ----- 15.5/17.7 MB 1.4 MB/s eta 0:00:02
   ---------------------------------- ----- 15.5/17.7 MB 1.4 MB/s eta 0:00:02
   ------------------------------------ --- 16.0/17.7 MB 1.4 MB/s eta 0:00:02
   ------------------------------------ --- 16.3/17.7 MB 1.4 MB/s eta 0:00:02
   ------------------------------------- -- 16.5/17.7 MB 1.4 MB/s eta 0:00:01
   ------------------------------------- -- 16.8/17.7 MB 1.4 MB/s eta 0:00:01
   -------------------------------------- - 17.0/17.7 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  17.3/17.7 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 17.7/17.7 MB 1.3 MB/s  0:00:13
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0
Note: you may need to restart the kernel to use updated packages.

In [34]:
import mysql.connector

# Connect to the server
db = mysql.connector.connect(
  host='127.0.0.1',
  user="root",
  password="qwertynoob",
  database="customer_behavior"
)

print(db)

<mysql.connector.connection_cext.CMySQLConnection object at 0x000001CE4FFF0830>

In [36]:
from sqlalchemy import create_engine

!pip install pymysql

engine = create_engine('mysql+pymysql://root:qwertynoob@127.0.0.1:3306/customer_behavior')

df.to_sql(name='customer', con=engine, if_exists='append', index=False)

print("Data loaded successfully!")

Collecting pymysql
  Downloading pymysql-1.1.3-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.3-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.3
Data loaded successfully!